export const FREE_LIMITS = {
  MESSAGES_PER_DAY: 20,
  WORKOUT_PLANS_PER_MONTH: 1,
  WORKOUT_PLAN_MODIFICATIONS_PER_MONTH: 3,
  BODY_HISTORY_DAYS: 14,
  MEAL_PLANS_LIFETIME: 1,
} as const;

export const PREMIUM_LIMITS = {
  MEAL_PLANS_PER_MONTH: 10,
} as const;
