export const FREE_LIMITS = {
  MESSAGES_PER_DAY: 20,
  WORKOUT_PLANS_PER_MONTH: 1,
  WORKOUT_PLAN_MODIFICATIONS_PER_MONTH: 3,
  BODY_HISTORY_DAYS: 14,
  MEAL_PLANS_LIFETIME: 1,
  MEAL_SWAPS_PER_WEEK: 3,
} as const;

export const MEAL_SWAP_PREVIEW_ATTEMPTS_MAX = 3;

export const PREMIUM_LIMITS = {
  MEAL_PLANS_PER_MONTH: 10,
} as const;
